apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-challenge-app
  namespace: devops-challenge
  labels:
    app: devops-challenge-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-challenge-app
  template:
    metadata:
      labels:
        app: devops-challenge-app
    spec:
      containers:
      - name: devops-challenge-app
        image: devops-challenge-app:latest #La imagen sera construida localmente por kind
        imagePullPolicy: IfNotPresent #Para usar la imagen loca del kind builder        
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: API_KEY
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 6
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits: 
            memory: "128Mi"
            cpu: "100m"