apiVersion: v1
kind: Service
metadata:
  name: devops-challenge-app-service
  namespace: devops-challenge
spec:
  selector:
    app: devops-challenge-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP # kind permite NodePort o LoadBalancer, pero ClusterIP es mas comun en servicios internos 